### ISSUE TITLE
problem when running python src/main.py  graph/karate.edgelist emb/karate.emd

### ISSUE THREAD

**Issue by wangxiaoyunanne** [aditya-grover/node2vec#11]
Traceback (most recent call last):
  File "src/main.py", line 104, in <module>
    main(args)
  File "src/main.py", line 100, in main
    learn_embeddings(walks)
  File "src/main.py", line 88, in learn_embeddings
    model.save_word2vec_format(args.output)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gensim/models/word2vec.py", line 1312, in save_word2vec_format
    raise DeprecationWarning("Deprecated. Use model.wv.save_word2vec_format instead.")
DeprecationWarning: Deprecated. Use model.wv.save_word2vec_format instead.

**Comment by wangxiaoyunanne** [comment]
solved, 
line 88 in main.py should be changed to  model.wv.save_word2vec_format

**Comment by carodak** [comment]
You saved my life. Thank you so much ! :1st_place_medal:

**Comment by Zhao-Cai** [comment]
thanks bro
