### ISSUE TITLE
im recieving this error 

### ISSUE THREAD

**Issue by hrdiva** [aditya-grover/node2vec#118]
!python node2vec/src/main.py --input diseasome.edgelist --output diseasome.emb --dimensions 32 --num-walks 20 --iter 10

Traceback (most recent call last):
  File "node2vec/src/main.py", line 15, in <module>
    import node2vec
  File "/content/node2vec/src/node2vec.py", line 46
    print 'Walk iteration:'
                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Walk iteration:')?

**Comment by networks1** [comment]
This was apparently written for Python2
