### ISSUE TITLE
DeprecationWarning: Deprecated. Use model.wv.save_word2vec_format instead.

### ISSUE THREAD

**Issue by yuedeji** [aditya-grover/node2vec#18]
I met this error when I tried to run the karate sample graph. I searched online and the reason is that gensim updates their word2vec model as shown here https://groups.google.com/forum/#!topic/gensim/pjZo1ZunIZA
Could you help to solve this issue?

Details:
python src/main.py --input graph/karate.edgelist
Walk iteration:
1 / 10
2 / 10
3 / 10
4 / 10
5 / 10
6 / 10
7 / 10
8 / 10
9 / 10
10 / 10
Traceback (most recent call last):
  File "src/main.py", line 104, in <module>
    main(args)
  File "src/main.py", line 100, in main
    learn_embeddings(walks)
  File "src/main.py", line 88, in learn_embeddings
    model.save_word2vec_format(args.output)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 1438, in save_word2vec_format
    raise DeprecationWarning("Deprecated. Use model.wv.save_word2vec_format instead.")
DeprecationWarning: Deprecated. Use model.wv.save_word2vec_format instead.

**Comment by carodak** [comment]
Got the same error here. Did you fix it ?

**Comment by yuedeji** [comment]
No, I didn't.
We can either try to use an older version of word2vec or change the source code of using word2vec. While, I am counting on the authors to fix this.
If you get any lucky, please let me know.

**Comment by carodak** [comment]
Hello,

I found the solution here :
https://github.com/aditya-grover/node2vec/issues/11

So he said : "line 88 in main.py should be changed to model.wv.save_word2vec_format"

Best reguards

**Comment by WillzZhu** [comment]
This change can make the code run. But the format of the embedding file is broken, which cannot be loaded again. Is there any solution to this problem?

**Comment by carodak** [comment]
I am not sure that I get it. Do you mean that this change broke your input
(adjacences matrixes) ? It doesn't do that to me. I can properly load again
and again my matrixes.
I made some change not loading adjacences from files but from my numpy
graphs. Anyway, it was working when I did it with adjacences list. I could
load the same adjacences list 2 times or more.

**Comment by carodak** [comment]
Sorry I mean that the input is adjacency list. And I can properly load them
again and again

**Comment by WillzZhu** [comment]
Oh the adjacency list (input) is fine, but my embedding matrix (output file) is broken, with wrong dimension (output [14, 128] while it should be [34, 128] in author's experiment), mixed with '[' and ']' symbols :(  

I'm sure the parser arguments are all correct.

**Comment by carodak** [comment]
I don't know what to say. I did not have such problems (I was using python
3, I made some change to make it work with python 3). The problem is that I
didn't take a look at my code since 3 months and I do not have a computer
with everything installed in atm. It's a bit messy, ahah. I can just
suggest to take a look at my code even if it's node2vec applied for
something else you may find something usefull.


2017-11-07 4:51 GMT+01:00 HZ <notifications@github.com>:

**Comment by alavertu** [comment]
Make sure you're using the correct python package versions. I'm using the python 2.7 and the package versions specified in the requirements.txt file, not having any issues.

**Comment by urmisaha** [comment]
Same for me. I used the exact versions specified in the requirements.txt file and the code ran successfully. I ran the following: pip install networkx==1.11 numpy==1.11.2 gensim==0.13.3
And then ran this: python src/main.py --input graph/karate.edgelist --output emb/karate.emd
Code ran successfully. :)

**Comment by king-zkai** [comment]
I'm using the python 2.7 and the package versions specified in the requirements.txt file, but the modules cannot be installed.
![图像 001](https://user-images.githubusercontent.com/50469192/59744964-46b4ef00-92a6-11e9-962c-80b9bca9b780.png)
![图像 002](https://user-images.githubusercontent.com/50469192/59744965-474d8580-92a6-11e9-8920-729d14a53e73.png)
![图像 003](https://user-images.githubusercontent.com/50469192/59744966-474d8580-92a6-11e9-9fff-2b2c0d105d7c.png)
How can I install the required modules correctly?
Thank you very much！

**Comment by amitmishramtech** [comment]
I am not getting any output graph just getting only 👍 
Walk iteration:
1 / 10
2 / 10
3 / 10
4 / 10
5 / 10
6 / 10
7 / 10
8 / 10
9 / 10
10 / 10
