### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'graph/karate.edgelist'

### ISSUE THREAD

**Issue by renmi001** [aditya-grover/node2vec#70]
problem when running main.py:
Traceback (most recent call last):
  File "D:/node2vec-master/src/main.py", line 104, in <module>
    main(args)
  File "D:/node2vec-master/src/main.py", line 96, in main
    nx_G = read_graph()
  File "D:/node2vec-master/src/main.py", line 73, in read_graph
    G = nx.read_edgelist(args.input, nodetype=int, create_using=nx.DiGraph())
  File "<D:\Anaconda2\lib\site-packages\decorator.pyc:decorator-gen-170>", line 2, in read_edgelist
  File "D:\Anaconda2\lib\site-packages\networkx\utils\decorators.py", line 198, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
IOError: [Errno 2] No such file or directory: 'graph/karate.edgelist'

but the file exists，so please help me solve this question,thank you !
![image](https://user-images.githubusercontent.com/49148700/56883577-ac9cab80-6a99-11e9-8843-bf4f89b45653.png)

**Comment by dongcy-AHU** [comment]
I have the same error with you.
Have you solved this problem yet?
Could you help me?Thank you very much!

**Comment by raulqf** [comment]
Maybe it's because the OS route path. Use os.path.join('graph','karate.edgelist') to define the input filename.

**Comment by dongcy-AHU** [comment]
> Maybe it's because the OS route path. Use os.path.join('graph','karate.edgelist') to define the input filename.

I try to import os module and modify the input filename to become
os.path.join('graph','karate.edgelist'),but still have the same problem FileNotFoundError: [Errno 2] No such file or directory: 'graph\\karate.edgelist'.

**Comment by raulqf** [comment]
Use the absolute path instead or the relative one to discard problems with the path.

**Comment by Jak32** [comment]
If you want relative path just change it like the image below. That happen because the main code runs on 'src' folder and not in root directory.
![image](https://user-images.githubusercontent.com/17153425/108639677-774b2400-749e-11eb-8988-fcee448ca748.png)
