### ISSUE TITLE
Where can I find ./spark-submit

### ISSUE THREAD

**Issue by ZhiyuanCao98** [aditya-grover/node2vec#78]
I am new to this Spark, I have cloned the program and do the `mvn clean package`, so How can I run the program?
I install the spark 2.4.3 and hadoop 3.1.2 in my own machine, but when I run the code, it shows: 

>  WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaMirrors$JavaMirror;
        at com.navercorp.Main$Params.<init>(Main.scala:15)
        at com.navercorp.Main$.<init>(Main.scala:32)
        at com.navercorp.Main$.<clinit>(Main.scala)
        at com.navercorp.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by devyrlee** [comment]
try this.
1. open ./node2vec/node2vec_spark/src/main/scala/com/navercorp/Main.scala
2. edit line 95
`def main(args: Array[String]) = { ` to
`def main(args: Array[String]) {`
(delete =)
3. save and mvn clean package
4. run!
